server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: 'ContasApagar'
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/contasapagar
    username: da
    password: c@ntAsApAgAr

  flyway:
    enabled: true
    locations: classpath:db/migration

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

jwt:
  private:
    key: classpath:private/app.key
  public:
    key: classpath:private/app.pub

info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'